################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Core/USER/APP/Pages/HeartRate/src \
Core/USER/APP/Pages/Startup/src \
Core/USER/APP/Pages/Template/src \
Core/USER/APP/Pages/src \
Core/USER/APP/Resource/Image \
Core/USER/APP/src \
Core/USER/Utils/Track_Parse/src \
Core/USER/Utils/lv_ext/src \
Drivers/BSP/GH3220/Algo_code/goodix_algo_application/src \
Drivers/BSP/GH3220/Algo_code/goodix_algo_call/src \
Drivers/BSP/GH3220/Kernel_code/driver/src \
Drivers/BSP/GH3220/Kernel_code/kernel/src \
Drivers/BSP/GH3220/Kernel_code/module/gh_agc \
Drivers/BSP/GH3220/Kernel_code/module/gh_ecg \
Drivers/BSP/GH3220/Kernel_code/module/gh_other \
Drivers/BSP/GH3220/Kernel_code/module/gh_protocol \
Drivers/BSP/GH3220/Kernel_code/module/gh_soft_adt \
Drivers/BSP/src \
Drivers/STM32F4xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/LVGL/GUI/lvgl/examples/porting \
Middlewares/LVGL/GUI/lvgl/src/core \
Middlewares/LVGL/GUI/lvgl/src/draw \
Middlewares/LVGL/GUI/lvgl/src/draw/nxp_pxp \
Middlewares/LVGL/GUI/lvgl/src/draw/nxp_vglite \
Middlewares/LVGL/GUI/lvgl/src/draw/sdl \
Middlewares/LVGL/GUI/lvgl/src/draw/stm32_dma2d \
Middlewares/LVGL/GUI/lvgl/src/draw/sw \
Middlewares/LVGL/GUI/lvgl/src/extra/layouts/flex \
Middlewares/LVGL/GUI/lvgl/src/extra/layouts/grid \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/bmp \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/ffmpeg \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/freetype \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/fsdrv \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/gif \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/png \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/qrcode \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/rlottie \
Middlewares/LVGL/GUI/lvgl/src/extra/libs/sjpg \
Middlewares/LVGL/GUI/lvgl/src/extra \
Middlewares/LVGL/GUI/lvgl/src/extra/others/gridnav \
Middlewares/LVGL/GUI/lvgl/src/extra/others/monkey \
Middlewares/LVGL/GUI/lvgl/src/extra/others/snapshot \
Middlewares/LVGL/GUI/lvgl/src/extra/themes/basic \
Middlewares/LVGL/GUI/lvgl/src/extra/themes/default \
Middlewares/LVGL/GUI/lvgl/src/extra/themes/mono \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/animimg \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/calendar \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/chart \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/colorwheel \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/imgbtn \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/keyboard \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/led \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/list \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/menu \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/meter \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/msgbox \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/span \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/spinbox \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/spinner \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/tabview \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/tileview \
Middlewares/LVGL/GUI/lvgl/src/extra/widgets/win \
Middlewares/LVGL/GUI/lvgl/src/font \
Middlewares/LVGL/GUI/lvgl/src/hal \
Middlewares/LVGL/GUI/lvgl/src/misc \
Middlewares/LVGL/GUI/lvgl/src/widgets \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \

